### ISSUE TITLE
broken stm32f7-discovery will fail travis even if fixed due to blinking_led example

### ISSUE THREAD

**Issue by oli-obk** [embed-rs/stm32f7-discovery#37]
The `blinking_led` example always checks out the master branch of the repository. But a pull request that fixes the project will not be in the master branch, so travis will fail.

We chose not to use a path dependency because it will allow copy pasting the `blinking_led` example anywhere. Not sure how to proceed here.

**Comment by phil-opp** [comment]
The `blinking_led` example is now a normal [Cargo example](https://doc.rust-lang.org/cargo/reference/manifest.html#examples) and no longer checks out the master branch.
