### ISSUE TITLE
RUST_TARGET_PATH

### ISSUE THREAD

**Issue by oli-obk** [embed-rs/stm32f7-discovery#6]
Apparently we have to set 

```
RUST_TARGET_PATH=`pwd`
```

before running xargo now, because the `stm32f7.json` isn't found anymore. Not sure how to solve this.

**Comment by phil-opp** [comment]
https://github.com/rust-lang-nursery/compiler-builtins/issues/87

**Comment by phil-opp** [comment]
With https://github.com/embed-rs/embedded-rs/commit/7d35074db109e713872c4f7e13b4d915cb5b2b6e, `RUST_TARGET_PATH` is no longer necessary.
