### ISSUE TITLE
Build currently fails due to invalid smoltcp branch

### ISSUE THREAD

**Issue by phil-opp** [embed-rs/stm32f7-discovery#79]
The pull request https://github.com/m-labs/smoltcp/pull/186 was forced-pushed, so the commit referenced in the Cargo.lock does no longer exist. Updating the Cargo.lock is not possible at the moment because the new branch contains an invalid Cargo.toml: https://github.com/m-labs/smoltcp/pull/186#discussion_r254349551.

I think the best solution is to wait a bit and hope that the pull request gets merged soon. If it takes to long, we can use an own fork the branch to ensure that no force-pushes occur.

**Comment by zshipko** [comment]
How can I help with getting this to build? I would really like to be able to use it for an upcoming project!

**Comment by oli-obk** [comment]
I think just running `cargo update` should do the trick

**Comment by phil-opp** [comment]
On the latest nightly the build still fails due to the updates to the futures/task API in https://github.com/rust-lang/rust/pull/57992. I tried to rebase our futures-rs fork for these changes: https://github.com/embed-rs/futures-rs/tree/alloc-rebase (I used a separate branch because I didn't test it yet). We also need to update our [`core` wrapper](https://github.com/embed-rs/stm32f7-discovery/blob/master/core/src/lib.rs) and the [`future_mutex`](https://github.com/embed-rs/stm32f7-discovery/blob/master/src/future_mutex.rs) and [`task_runtime`](https://github.com/embed-rs/stm32f7-discovery/blob/master/src/task_runtime.rs) modules.

**Comment by oli-obk** [comment]
I'm gonna finish the rebases and updates
